### PR TITLE
Rustup to "rustc 1.56.0-nightly (6d64f7f69 2021-08-19)"

### LINKED ISSUE #8: Update to newer rust version?
The rust version in the Dockerfile is from about one year ago, and a lot of new features have been implemented since then.

https://github.com/sslab-gatech/Rudra/blob/a2ea65cad7c3fc30c5f8d29a62411e0236af2a2c/Dockerfile#L8

I tried to change the rust version in the Dockerfile to the latest nightly:
```diff
-     RUST_VERSION=nightly-2020-08-26 \
+     RUST_VERSION=nightly-2021-08-20 \
```

which resulted in a compilation failure:
```
   Compiling rudra v0.1.0 (/tmp/rudra)
error[E0463]: can't find crate for `rustc_data_structures`
 --> src/lib.rs:7:1
  |
7 | extern crate rustc_data_structures;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `rudra`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rudra v0.1.0 (/tmp/rudra)`, intermediate artifacts can be found at `/tmp/rudra/target`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes #8 

Based on #9

### CODE REVIEW

**Comment by Qwaz** [comment]
Hello, thank you very much for this PR! Right now, there is an ongoing [artifact evaluation](https://sysartifacts.github.io/sosp2021/index.html) for this project, so we need to keep the master branch close to the submitted version of the paper for a while. We will merge this PR after the evaluation, which I expect to take a few weeks.

**Comment by bjorn3** [comment]
Sure. No problem.

**Comment by Qwaz** [comment]
Yes!

**Comment by bjorn3** [comment]
Rebased

**Comment by Qwaz** [comment]
Thank you very much!

**Comment by Qwaz** [comment]
This line panics after merge. Do you have any idea how to fix it?
```rust
                        if tcx.subst_and_normalize_erasing_regions(
                                callee_substs,
                                ParamEnv::reveal_all(),
                                pointed_ty,
                            )
                            .is_copy_modulo_regions(tcx.at(DUMMY_SP), tcx.param_env(callee_did));
```

Backtrace:
```
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:538:17: type parameter `U/#1` (U/1) out of range when substituting, substs=[U]

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/6d64f7f695943541fe12bb960971403f440d7225/compiler/rustc_errors/src/lib.rs:1061:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::span_bug
   3: rustc_errors::Handler::span_bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::span_bug_fmt
   7: <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
   8: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::fold_with
             at /rustc/6d64f7f695943541fe12bb960971403f440d7225/compiler/rustc_middle/src/ty/structural_impls.rs:899:9
   9: <T as rustc_middle::ty::subst::Subst>::subst_spanned
             at /rustc/6d64f7f695943541fe12bb960971403f440d7225/compiler/rustc_middle/src/ty/subst.rs:429:9
  10: rustc_middle::ty::subst::Subst::subst
             at /rustc/6d64f7f695943541fe12bb960971403f440d7225/compiler/rustc_middle/src/ty/subst.rs:410:9
  11: rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::subst_and_normalize_erasing_regions
             at /rustc/6d64f7f695943541fe12bb960971403f440d7225/compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:81:27
  12: rudra::analysis::unsafe_dataflow::inner::fn_called_on_copy
             at /home/yechan/rudra-project/rudra/src/analysis/unsafe_dataflow.rs:299:28
  13: rudra::analysis::unsafe_dataflow::inner::UnsafeDataflowBodyAnalyzer::analyze
             at /home/yechan/rudra-project/rudra/src/analysis/unsafe_dataflow.rs:186:32
  14: rudra::analysis::unsafe_dataflow::inner::UnsafeDataflowBodyAnalyzer::analyze_body
             at /home/yechan/rudra-project/rudra/src/analysis/unsafe_dataflow.rs:160:30
  15: rudra::analysis::unsafe_dataflow::UnsafeDataflowChecker::analyze
             at /home/yechan/rudra-project/rudra/src/analysis/unsafe_dataflow.rs:55:35
  16: rudra::analyze::{{closure}}
             at /home/yechan/rudra-project/rudra/src/lib.rs:137:13
  17: rudra::run_analysis
             at /home/yechan/rudra-project/rudra/src/lib.rs:103:18
  18: rudra::analyze
             at /home/yechan/rudra-project/rudra/src/lib.rs:135:9
  19: <rudra::RudraCompilerCalls as rustc_driver::Callbacks>::after_analysis::{{closure}}
             at /home/yechan/rudra-project/rudra/src/bin/rudra.rs:48:13
```

Related: #17

**Comment by bjorn3** [comment]
I think it needs the caller substs and not callee substs as the argument type is extracted from the caller body and not the callee body.

**Comment by Qwaz** [comment]
`SubstsRef` and `ParamEnv` always confuse me 😇 I think we actually had a bug in false positive filtering routine in the version that we submitted to the conference. I hope that my last commit fixes it.

**Pull request merged**
